### ISSUE TITLE
Default to Module::Build::Tiny?

### ISSUE THREAD

**Issue by karenetheridge** [tokuhirom/Minilla#164]
Currently, Minilla defaults to using Module::Build, which is not very "minimalistic" - in fact it's pretty awful, and we at the Toolchain Gang are trying to phase things away from using it whenever possible.

Would it be possible for Minilla to default to using Module::Build::Tiny instead of Module::Build?  I do not know if it would break anything.

**Comment by Grinnz** [comment]
To note, this would also match the current default for Dist::Milla.

**Comment by miyagawa** [comment]
I guess the decision is very subjective, and I personally don't have a strong opinion on this, but +1 on making MBT a default because:

* matches with Milla's default
* The Build.PL template Minilla creates (with File::Copy etc.) is a horrible hack, and MBT does it so much better without these nasty code.
* MBT will bring a few dependencies (configure_requires) only once per perl install, but Module::Build on 5.20+ will do the same.

The only thing you have to consider is an existing users with XS code in there, expecting Module::Build to be the default. I'm sure you can add some transitional code that detects XS code in a project and warns if installer is not set.

**Comment by Leont** [comment]
+1 on everything miyagawa just said

**Comment by tokuhirom** [comment]
:+1: patches welcome :P

**Comment by karenetheridge** [comment]
ok, I'll try to do a patch :)

one thing confuses me:  Minilla::Profile::Default has:
    use parent qw(Minilla::Profile::ModuleBuildTiny);

...so why is it defaulting to Module::Build instead?

**Comment by miyagawa** [comment]
I think there's a bug in the Profile class where ModuleBuildTiny and ModuleBuild profile are actually identical.

**Comment by miyagawa** [comment]
nevermind - yes, for new projects it definitely creates ModuleBuildTiny as a default builder. dabf5aaae1e7896ad078b6170024fa5476c22f8a

**Comment by miyagawa** [comment]
The only code path where ModuleBuild is loaded is when a config file `minil.toml` does not exist, or when `module_maker=` is not set, if I understand the code correctly.

**Comment by karenetheridge** [comment]
if `module_maker=` is not set in new projects being created, wouldn't that mean it would still default to ModuleBuild?

**Comment by Leont** [comment]
> if module_maker= is not set in new projects being created, wouldn't that mean it would still default to ModuleBuild?

I think it means that dists minted before the change continue to use ModuleBuild, while dists minted after will use ModuleBuildTiny.
